### ISSUE TITLE
Add the option to provide the python_version on any command

### ISSUE THREAD

**Issue by joepreludian** [darwin67/chef-pyenv#32]
Would be nice to add a param to the resources of the cookbook in order to override the version of python.

For example:

```
pyenv_pip 'requests' do
  version '2.18.3'
  python_version '2.7.15'
end
```

This would update the requests library inside the python version 2.7.15 (let's suppose that the python version number 2.7.15 is already installed)

How it sounds like?

In other words, it's just a matter of using "PYTHON_VERSION" environment variable before any python/pip command.

**Comment by darwin67** [comment]
Could you clarify what you mean by using the `PYTHON_VERSION` environment variable?

Also, what is the use case of this?

**Comment by joepreludian** [comment]
Sure,

Suppose that we need to maintain two projects into different versions of
python. I faced some projects running on python 2 and other ones running
into python 3 on the same host. Would be awesome that we could manage their
dependencies independently by setting which version of python we
should use, and plus, running python scripts selecting the proper version
of python.

If you want I can describe more in detail, but in the nutshell that is the
meaning of creating an optional param.

**Comment by darwin67** [comment]
Looks like that is something that can be achieved with the `virtualenv` option?
Did you give it a try?

https://github.com/darwin67/chef-pyenv/blob/master/resources/pip.rb#L24

**Comment by joepreludian** [comment]
But even with a different python version or it will depends of the running
global version of python? Virtualenv uses a version of python installed in
order to create a virtualenv. I guess that that code is coupled because on
virtualenv you ought to provide a python version as an optional param.
Isn't?

If I wish to install a python package was a "system" dependency In an non
global python it won't be possible. Right?

And I haven't found the code responsible for creating a virtualenv with the
version of python. As far as I know it will only use the global version
instead.

Oh. There is a workaround. If I set the global python pointing to one
version, install the pip packages and then turn back the python global.

Thanks and sorry for adding too much complexity. Haha
But it stills useful when dealing mainly with systems that is transitioning
from python 2 to 3 and needs to exists at the same machine.

**Comment by darwin67** [comment]
> And I haven't found the code responsible for creating a virtualenv with the
version of python. As far as I know it will only use the global version
instead.

Yes, that part doesn't exist yet. So the virtualenv will depend on the python version available at the time when you created the virtualenv.
It might make sense for `pyenv_script` to accept an argument to tell it which python version to run it in. :)

I'll be happy to review if you want to create a PR for that. 

> Oh. There is a workaround. If I set the global python pointing to one
version, install the pip packages and then turn back the python global.

Ah yes, like you said in the case for transition, that's basically what I do. Install one python version and the pip packages before moving on to the next.

```ruby
['2.7', '3.7'].each do |version|
  pyenv_python version

  pyenv_global version

  node['mycookbook']['packages'].each do |pkg| => # an array of python packages to be installed.
    pyenv_pip pkg
  end
end
```

**Comment by darwin67** [comment]
Looks like this is pretty much resolved, closing.
