### ISSUE TITLE
pyenv_python needs umask option

### ISSUE THREAD

**Issue by volker-fr** [darwin67/chef-pyenv#4]
`pyenv_python` needs the `umask` option. If the `umask` of the user that executes `chef-client` is wrong the pyenv won't be accessible by every user.

**Comment by joepreludian** [comment]
Hello @volker-fr. How this umask option should be set?

**Comment by volker-fr** [comment]
0022 is usually a the permission you want to provide to grant read and execute permissions to the user and the group.
