### ISSUE TITLE
Set working default kitchen.yml values.  Document test setup requirements.

### ISSUE THREAD

**Issue by hedgehog** [darwin67/chef-pyenv#48]
### Cookbook version
`master`

### Chef-client version
ChefDK 3.11.3

### Platform Details
Ubuntu 18.04

### Scenario:
Run test suite before making PR.

### Steps to Reproduce:
```
git clone ....
cd chef-pyenv
kitchen test
```
### Expected Result:
Green tests

### Actual Result:
Various errors related to Ominbus truck artifact repository.  Example
```
ERROR 404
       Omnitruck artifact does not exist for version current on platform el
       
       Either this means:
          - We do not support el
          - We do not have an artifact for current
       
       This is often the latter case due to running a prerelease or RC version of chef
       or a gem version which was only pushed to rubygems and not omnitruck.
       
       You may be able to set your knife[:bootstrap_version] to the most recent stable
       release of Chef to fix this problem (or the most recent stable major version number).
       
       In order to test the version parameter, adventurous users may take the Metadata URL
       below and modify the '&v=<number>' parameter until you successfully get a URL that
       does not 404 (e.g. via curl or wget).  You should be able to use '&v=11' or '&v=12'
       succesfully.
       
       If you cannot fix this problem by setting the bootstrap_version, it probably means
       that el is not supported.
       
       Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=current&p=el&pv=6&m=x86_64
```

Does the `kitchen.yml` actually do anything?  

I had some success with `kitchen.dokken.yml`....

Will you accept a PR switchen them around?:
`kitchen.yml -> kitchen.vagrant.yml`
`kitchen.dokken.yml -> kitchen.yml`

**Comment by darwin67** [comment]
That is intentional so it's easier for me to switch between chef versions without modifying `.kitchen.yml` every single time.

https://github.com/darwin67/chef-pyenv/blob/master/.kitchen.yml#L8

**Comment by hedgehog** [comment]
Understood. I've updated the issue subject to reflect this. However the default setup is broken. 

given the existing config is broken by default, I suggest the less frustrating default value is to use the minimal Che version you expect all tests to be green?
